- name: Preparing the c_adx_ipgm directory.
  include_role:
    name: installation
    tasks_from: Erase_ACE.yml
  when: opc  == "1"

- name: Check ACE4D Exist
  stat:
    path: "{{c_drive}}ACE4D/"
  register: ace4d

- name: Cleanning ACE4D if exist
  shell: "rm -r {{c_drive}}ACE4D/"
  when: ace4d.stat.exists

- name: Create Directory ACE4D If Does Not Exist
  file:
    path: "{{c_drive}}ACE4D/"
    state: directory

- name: Download Toshiba Nexus Package ACE EPS From Nexus
  get_url:
    url: "{{nexus_url2}}/repository/tgcs-maven-snapshot/com/toshibacommerce/ace/ACE4D001/{{level_name}}-SNAPSHOT/ACE4D001-{{level_complementEPS}}.zip"
    dest: "{{landing_zone}}"

- name: Copy ACE4D
  shell: "cp {{landing_zone}}ACE4D001-{{level_complementEPS}}.zip {{c_drive}}ACE4D/ACE4D001.zip; cp {{landing_zone}}asm.py {{c_adx_imnt}}/;"

- name: Unziping the package of installation
  shell: "python3 {{c_adx_imnt}}UINSTALL/unZIP.PY"

- name: Updating the installation files 
  shell: "python3 {{c_adx_imnt}}UINSTALL/updFile.py"

- name: Printing opc ACE3D
  shell: "echo {{opc}} >> {{c_adx_imnt}}UINSTALL/START4D.BAT"

- name: Starting the installation
  shell: "{{c_adx_imnt}}UINSTALL/START4D.BAT"

- name: Starting asm and reboot controller...
  shell: "python2 {{c_adx_imnt}}asm.py {{ASM}} AI"
  ignore_errors: true
